- name: Python bootstrap
  include_tasks: python_bootstrap.yml
  when: hypervisor_install_python and provision_mode

#- name: Get vars
#  setup:
#  delegate_to: "{{ hypervisor_host }}"
#  when: provision_mode

- name: Get virtual machine uuid
  command: vmadm list -o uuid -p hostname={{ alias }}.{{ domain }}
  delegate_to: "{{ hypervisor_host }}"
  register: vmadm_list
  changed_when: false

- name: Machine exists message
  debug:
    msg: "{{ alias }}.{{ domain }} already exists"
  when: vmadm_list.stdout | length == 36

- name: Add vm
  include_tasks: add_vm.yml
  when:
    - provision_mode
    - vmadm_list.stdout | length == 0

- name: Add fwadm remote vms
  include_tasks: add_fwadm_remote_vms.yml
