- include: python_bootstrap.yml
  delegate_to: "{{ hypervisor_host }}"
  when: hypervisor_install_python and provision_mode

- name: Get vars
  setup:
  delegate_to: "{{ hypervisor_host }}"
  when: provision_mode

# First check if VM is already provisioned



- include: images.yml
  delegate_to: "{{ hypervisor_host }}"
  when: provision_mode

# - name: Get virtual machine uuid
#   command: vmadm list -o uuid -p hostname={{ alias }}.{{ domain }}
#   delegate_to: "{{ hypervisor_host }}"
#   register: vmadm_list
# 
# - name: set running machine
#   delegate_to: "{{ hypervisor_host }}"
#   set_fact: vm_uuid={{ vmadm_list.stdout }}
# 
# - debug: var=vm_uuid
# 
# - name: Get virtual info
#   command: vmadm get {{ vm_uuid }}
#   delegate_to: "{{ hypervisor_host }}"
#   register: vm_info
# 
# - debug: var=vm_info
# 
# - fail: msg="blah"

- name: Creating Ansible tmp file for vm .json
  command: mktemp /tmp/ansible.XXXXXXX
  register: tmp_json
  delegate_to: "{{ hypervisor_host }}"
  when: provision_mode

- name: Populating template file
  template: src={{ template_file }} dest={{ tmp_json.stdout }}
  delegate_to: "{{ hypervisor_host }}"
  when: provision_mode

- name: Provisioning virtual machine
  shell: cat {{ tmp_json.stdout }} | vmadm create
  delegate_to: "{{ hypervisor_host }}"
  when: provision_mode

- name: Waiting 10 secs for SSH daemon
  wait_for:
    host: "{{ nics[0]['ip'] }}"
    port: 22
    search_regex: OpenSSH
  delegate_to: "{{ hypervisor_host }}"
  when: provision_mode
